version: 0.1

phases:
  install:
    commands:
      - echo install started on `date`
      - pwd
      - gem list
      - bundle install
  build:
    commands:
      - echo Build started on `date`
      - bundle exec rspec
  post_build:
    commands:
      - echo Build completed on `date`
